### PR TITLE
Profiles and components support

### PR DESCRIPTION
**Pull request by svartalf**

### CODE REVIEW

**Comment by ubnt-intrepid** [comment]
[Here](https://github.com/ubnt-intrepid/polyfuse/commit/f45ba6d10555ddbbd4122f43e1219db10f4e718f/checks?check_suite_id=269913944) is a result obtained from my project.

Observations:

* In the case using the GitHub's environment directly, the installation of toolchain with `profile: minimal` seems to be worked as expected.
* When using the Docker container (in this case `rustops/crates-build-env`), an `EACCES` is reported and the installation is failed:

<details>

```
Run actions-rs/toolchain@profiles
  with:
    profile: minimal
    toolchain: nightly
    override: true
    default: false
/usr/bin/docker exec  821786e5c1acb7186860b714748ac0a29c428b85a9d8c851ac9e8284a45a5e07 sh -c "cat /etc/*release | grep ^ID"
Running JavaScript Action with default external tool: node12
/__w/_temp/ddc720e7-fa3b-41ab-8d3e-9480da892c33 --default-toolchain none
##[error]There was an error when attempting to execute the process '/__w/_temp/ddc720e7-fa3b-41ab-8d3e-9480da892c33'. This may indicate the process failed to start. Error: spawn /__w/_temp/ddc720e7-fa3b-41ab-8d3e-9480da892c33 EACCES
##[error]Node run failed with exit code 1
```
</details>

The difference between the above two cases is whether or not the `rustup` is already installed (in `rustops/crates-build-env`, rustup is not installed), and its difference appears as the presence or absence of calling `Rustup.install`.

It is just my guess, but it might be necessary to add the executable permission to the downloaded script [at here](https://github.com/actions-rs/core/blob/master/src/commands/rustup.ts#L54)?;

**Comment by svartalf** [comment]
TIL: JS-based Actions can be executed in the Docker containers too.
Yeah, it seems that we need to add the executable bit manually, added in the 1091bc95e8ac697c5b4bd485d01763cec910fe19; @ubnt-intrepid, could you restart your workflow?

**Comment by ubnt-intrepid** [comment]
@svartalf CI result after restart: https://github.com/ubnt-intrepid/polyfuse/commit/2ad4ce771bbf67ce2297dba8c1ab32fd9f599063/checks?check_suite_id=270433394

* Adding execute permission works fine.
* `rustup-init` fails due to missing `-y` option:

```
...
info: downloading installer
rustup: Unable to run interactively. Run with -y to accept defaults, --help for additional options
##[error]The process '/__w/_temp/ff8a4756-3978-4d64-9e61-1b314d34b76d' failed with exit code 1
##[error]Node run failed with exit code 1
```

**Comment by svartalf** [comment]
@ubnt-intrepid okay, I fixed that too and added a few integration tests also in order to stop bother you with the constant restarts: https://github.com/actions-rs/toolchain/runs/265108596 (ignore failing `check_pr` job)

One thing I noticed is that `rustup` needs `curl` or `wget`, so if none of them are available in the container, execution will fail; I suppose that it is out of our scope, at least `rustup` shows a proper message about it.

Could you restart your workflow one last time? :)

**Comment by ubnt-intrepid** [comment]
@svartalf [It works as we expected!](https://github.com/ubnt-intrepid/polyfuse/pull/20/checks?check_run_id=265157386#step:5:18)

**Pull request merged**
